FROM node:20-alpine

WORKDIR /app

RUN corepack enable

RUN apk add --no-cache curl unzip bash && \
    curl -fsSL https://bun.sh/install | bash && \
    ln -s /root/.bun/bin/bun /usr/local/bin/bun && \
    ln -s /root/.bun/bin/bunx /usr/local/bin/bunx

ENTRYPOINT ["sh", "docker/entrypoint.sh"]

EXPOSE 3000
